-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
WHERE A.ITEM_ID NOT IN (
    SELECT B.PARENT_ITEM_ID
    FROM ITEM_TREE B
    WHERE B.PARENT_ITEM_ID IS NOT NULL # PARENT_ID가 NULL 인것을 배제
    # 이 쿼리에서 최종적으로 0, 1이 남음
)
ORDER BY A.ITEM_ID DESC;