SELECT u.USER_ID, u.NICKNAME, CONCAT(u.CITY, " ",TRIM(u.STREET_ADDRESS1), " " , u.STREET_ADDRESS2) AS "전체 주소", CONCAT(SUBSTRING(u.TLNO, 1, 3), "-", SUBSTRING(u.TLNO, 4, 4), "-", SUBSTRING(u.TLNO, 8, 4)) AS "전화번호"
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
GROUP BY b.WRITER_ID
HAVING COUNT(b.WRITER_ID) >= 3
ORDER BY u.USER_ID DESC