SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;