-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (MAX_TABLE.MAX_COLONY - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS MAX_TABLE ON YEAR(DIFFERENTIATION_DATE) = MAX_TABLE.YEAR
ORDER BY YEAR, YEAR_DEV;