-- 코드를 작성해주세요
SELECT A.ID , B.FISH_NAME , A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
    SELECT MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_TABLE
ON A.FISH_TYPE = MAX_TABLE.FISH_TYPE AND A.LENGTH = MAX_TABLE.MAX_LENGTH
ORDER BY A.ID;